### ISSUE TITLE
please stop subscribing me to your repositories.

### ISSUE THREAD

**Issue by axb21** [athenahealth/docker-ruby#1]
You have subscribed me to multiple athenahealth repositories over the past year, including two today. Please stop. I am in no way associated with this codebase nor interested in contributing to it.

Thank you.

**Comment by salekseev** [comment]
Hello good sir. Unfortunately I didn't subscribe you to our repositories (and I don't suppose it's possible without you clicking the watch button yourself) and this could be a bug in github.com. I suggest you open a support ticket with them.
